Fix base64_test pointer-sign warnings
When running "make check" with CFLAGS="-Wall -Werror", gcc 4.9.2 on
Debian 8.6 generates 16 "pointer-sign" errors in base64_test.c in
calls to strlen() and strncmp():

> base64_test.c: In function 'validate':
> base64_test.c:76:45: error: pointer targets in passing argument 1
>       of 'strlen' differ in signedness [-Werror=pointer-sign]
>      if (encode_block (buf, &n, src, strlen (src)) < 0)
>                                              ^
> In file included from base64_test.c:31:0:
> /usr/include/string.h:399:15: note: expected 'const char *'
>       but argument is of type 'const unsigned char *'
>  extern size_t strlen (const char *__s)
>                ^

> base64_test.c:80:18: error: pointer targets in passing argument 1
>       of 'strncmp' differ in signedness [-Werror=pointer-sign]
>      if (strncmp (dst, buf, n))
>                   ^
> In file included from base64_test.c:31:0:
> /usr/include/string.h:147:12: note: expected 'const char *'
>       but argument is of type 'const unsigned char *'
>  extern int strncmp (const char *__s1, const char *__s2, size_t __n)
>             ^

This commit revamps the test code to fix all compiler warnings.
The unsigned type qualifier is removed from the dst arrays.  The
terminating null character is removed from the src arrays since they
are not technically strings; their length is now computed via sizeof
instead of strlen().  The src arrays are now passed as "void *"; since
encode_context() and decode_context() do pointer arithmetic with the
src parm, this parm is casted to a local "const unsigned char *" var.
Function prototypes are updated accordingly.

Signed-off-by: Chris Dunlap <cdunlap@llnl.gov>